<?php
require_once(dirname(__FILE__) . '/../../phpunit/DbHero_TestCase.php');
require_once( FRAMEWORK_PATH . 'collections/UnifiedOrderCollection.php' );

/**
 * Class GeneralActivityCollectionTest
 */
class UnifiedOrderCollectionTest extends DbHero_TestCase {

    /**
     * @return PHPUnit_Extensions_Database_DataSet_IDataSet
     */
    public function getDataSet() {
        $dataSet = new PHPUnit_Extensions_Database_DataSet_CsvDataSet();
        $dataSet->addTable('wholesale_product', dirname(__FILE__)."/UnifiedOrderCollection/wholesale_product.csv");
        $dataSet->addTable('wholesale_product_spec', dirname(__FILE__)."/UnifiedOrderCollection/wholesale_product_spec.csv");
        $dataSet->addTable('groupbuying_activity', dirname(__FILE__)."/UnifiedOrderCollection/groupbuying_activity.csv");
        $dataSet->addTable('consumer_user', dirname(__FILE__)."/UnifiedOrderCollection/consumer_user.csv");
        $dataSet->addTable('general_activity', dirname(__FILE__)."/UnifiedOrderCollection/general_activity.csv");
        $dataSet->addTable('unified_order', dirname(__FILE__)."/UnifiedOrderCollection/unified_order.csv");
        $dataSet->addTable('order_has_spec', dirname(__FILE__)."/UnifiedOrderCollection/order_has_spec.csv");

        return $dataSet;
    }

    /**
 * Test search fare's records
 * @dataProvider searchRecordsProvider
 */
    public function testSearchRecords($describe, $params, $expected) {
        echo "$describe \n\r ";
        $collection = new UnifiedOrderCollection();
        $result = $collection->searchRecords(1, 1000, $params);
        $this->assertEquals($expected, $result);
    }

    public function searchRecordsProvider() {
        return array(
            array(
                //Describe
                "Search UnifiedOrder record by keyword [Rex] .",
                // params
                array("keyword" => "Rex" ),
                // expected
                json_decode('
                   {
                        "records": [{
                         "id": "1",
                         "activity_id": "2",
                         "activity_type": "groupbuying",
                         "consumer_user_id": "1",
                         "buyer_name": "Rex",
                         "buyer_phone_number": "0972831678",
                         "buyer_email": "chen.cyr@gmail.com",
                         "product_total_price": "35200",
                         "final_total_price": "35200",
                         "other_cost": "0",
                         "cost_type": "normal",
                         "fare": "0",
                         "fare_type": "\u5b85\u914d",
                         "fare_id": "3",
                         "discount": "0",
                         "discount_type": "normal",
                         "payment_type": "0",
                         "receiver_address": "\u53f0\u5317\u5e02\u4fe1\u7fa9\u5340\u5b89\u548c\u8def\u4e00\u6bb589\u865f",
                         "receiver_name": "Rex",
                         "receiver_phone_number": "0972831678",
                         "state": "12",
                         "create_datetime": "2015-09-13 03:31:15",
                         "pay_notify_datetime": "2015-09-13 03:35:15",
                         "serial": "201509131Tpt2",
                         "delivery_datetime": "2015-09-21 20:14:08",
                         "delivery_channel": "\u4fbf\u5229\u5e36",
                         "delivery_number": "GH11563",
                         "close_datetime": "2015-10-19 06:47:39",
                         "inventory_process": "1",
                         "user_name": "groupbuying",
                         "user_account": "groupbuying@109life.com",
                         "user_email": "groupbuying@109life.com",
                         "stateText": "returned"
                     }, {
                         "id": "13",
                         "activity_id": "1",
                         "activity_type": "general",
                         "consumer_user_id": "1",
                         "buyer_name": "Rex",
                         "buyer_phone_number": "0972831678",
                         "buyer_email": "chen.cyr@gmail.com",
                         "product_total_price": "26700",
                         "final_total_price": "26700",
                         "other_cost": "0",
                         "cost_type": "normal",
                         "fare": "0",
                         "fare_type": "\u5b85\u914d",
                         "fare_id": "3",
                         "discount": "0",
                         "discount_type": "normal",
                         "payment_type": "0",
                         "receiver_address": "\u53f0\u5317\u5e02\u4fe1\u7fa9\u5340\u5b89\u548c\u8def\u4e00\u6bb589\u865f",
                         "receiver_name": "Rex",
                         "receiver_phone_number": "0972831678",
                         "state": "12",
                         "create_datetime": "2015-09-13 03:31:15",
                         "pay_notify_datetime": "2015-09-13 03:35:15",
                         "serial": "201509131Tpt9",
                         "delivery_datetime": "2015-09-21 20:14:08",
                         "delivery_channel": "\u4fbf\u5229\u5e36",
                         "delivery_number": "GH11563",
                         "close_datetime": "2015-10-19 06:20:22",
                         "inventory_process": "1",
                         "user_name": "groupbuying",
                         "user_account": "groupbuying@109life.com",
                         "user_email": "groupbuying@109life.com",
                         "stateText": "returned"
                     }, {
                         "id": "18",
                         "activity_id": "1",
                         "activity_type": "reorder_general",
                         "consumer_user_id": "1",
                         "buyer_name": "Rex",
                         "buyer_phone_number": "0972831678",
                         "buyer_email": "chen.cyr@gmail.com",
                         "product_total_price": "17800",
                         "final_total_price": "17900",
                         "other_cost": "0",
                         "cost_type": "normal",
                         "fare": "100",
                         "fare_type": "\u5b85\u914d",
                         "fare_id": "3",
                         "discount": "0",
                         "discount_type": "normal",
                         "payment_type": "0",
                         "receiver_address": "\u53f0\u5317\u5e02\u4fe1\u7fa9\u5340\u5b89\u548c\u8def\u4e00\u6bb589\u865f",
                         "receiver_name": "Rex",
                         "receiver_phone_number": "0972831678",
                         "state": "4",
                         "create_datetime": "2015-10-19 06:20:22",
                         "pay_notify_datetime": "2015-10-19 06:20:22",
                         "serial": "20151019kk7ws",
                         "delivery_datetime": "2015-09-21 20:14:08",
                         "delivery_channel": "\u4fbf\u5229\u5e36",
                         "delivery_number": "GH11563",
                         "close_datetime": "0000-00-00 00:00:00",
                         "inventory_process": "1",
                         "user_name": "groupbuying",
                         "user_account": "groupbuying@109life.com",
                         "user_email": "groupbuying@109life.com",
                         "stateText": "completed"
                     }, {
                         "id": "19",
                         "activity_id": "2",
                         "activity_type": "reorder_groupbuying",
                         "consumer_user_id": "1",
                         "buyer_name": "Rex",
                         "buyer_phone_number": "0972831678",
                         "buyer_email": "chen.cyr@gmail.com",
                         "product_total_price": "26400",
                         "final_total_price": "26400",
                         "other_cost": "0",
                         "cost_type": "normal",
                         "fare": "0",
                         "fare_type": "\u5b85\u914d",
                         "fare_id": "3",
                         "discount": "0",
                         "discount_type": "normal",
                         "payment_type": "0",
                         "receiver_address": "\u53f0\u5317\u5e02\u4fe1\u7fa9\u5340\u5b89\u548c\u8def\u4e00\u6bb589\u865f",
                         "receiver_name": "Rex",
                         "receiver_phone_number": "0972831678",
                         "state": "4",
                         "create_datetime": "2015-10-19 06:47:39",
                         "pay_notify_datetime": "2015-10-19 06:47:39",
                         "serial": "20151019OPewM",
                         "delivery_datetime": "2015-09-21 20:14:08",
                         "delivery_channel": "\u4fbf\u5229\u5e36",
                         "delivery_number": "GH11563",
                         "close_datetime": "0000-00-00 00:00:00",
                         "inventory_process": "1",
                         "user_name": "groupbuying",
                         "user_account": "groupbuying@109life.com",
                         "user_email": "groupbuying@109life.com",
                         "stateText": "completed"
                     }],
                     "pageNo": 1,
                     "pageSize": 1000,
                     "totalPage": 1,
                     "recordCount": 4
                 }
                ', true)
            ),
            array(
                //Describe
                "Search UnifiedOrder record by keyword [GH11563] .",
                // params
                array("keyword" => "GH11563" ),
                // expected
                json_decode('
                        {
                        "records": [{
                         "id": "1",
                         "activity_id": "2",
                         "activity_type": "groupbuying",
                         "consumer_user_id": "1",
                         "buyer_name": "Rex",
                         "buyer_phone_number": "0972831678",
                         "buyer_email": "chen.cyr@gmail.com",
                         "product_total_price": "35200",
                         "final_total_price": "35200",
                         "other_cost": "0",
                         "cost_type": "normal",
                         "fare": "0",
                         "fare_type": "\u5b85\u914d",
                         "fare_id": "3",
                         "discount": "0",
                         "discount_type": "normal",
                         "payment_type": "0",
                         "receiver_address": "\u53f0\u5317\u5e02\u4fe1\u7fa9\u5340\u5b89\u548c\u8def\u4e00\u6bb589\u865f",
                         "receiver_name": "Rex",
                         "receiver_phone_number": "0972831678",
                         "state": "12",
                         "create_datetime": "2015-09-13 03:31:15",
                         "pay_notify_datetime": "2015-09-13 03:35:15",
                         "serial": "201509131Tpt2",
                         "delivery_datetime": "2015-09-21 20:14:08",
                         "delivery_channel": "\u4fbf\u5229\u5e36",
                         "delivery_number": "GH11563",
                         "close_datetime": "2015-10-19 06:47:39",
                         "inventory_process": "1",
                         "user_name": "groupbuying",
                         "user_account": "groupbuying@109life.com",
                         "user_email": "groupbuying@109life.com",
                         "stateText": "returned"
                     }, {
                         "id": "13",
                         "activity_id": "1",
                         "activity_type": "general",
                         "consumer_user_id": "1",
                         "buyer_name": "Rex",
                         "buyer_phone_number": "0972831678",
                         "buyer_email": "chen.cyr@gmail.com",
                         "product_total_price": "26700",
                         "final_total_price": "26700",
                         "other_cost": "0",
                         "cost_type": "normal",
                         "fare": "0",
                         "fare_type": "\u5b85\u914d",
                         "fare_id": "3",
                         "discount": "0",
                         "discount_type": "normal",
                         "payment_type": "0",
                         "receiver_address": "\u53f0\u5317\u5e02\u4fe1\u7fa9\u5340\u5b89\u548c\u8def\u4e00\u6bb589\u865f",
                         "receiver_name": "Rex",
                         "receiver_phone_number": "0972831678",
                         "state": "12",
                         "create_datetime": "2015-09-13 03:31:15",
                         "pay_notify_datetime": "2015-09-13 03:35:15",
                         "serial": "201509131Tpt9",
                         "delivery_datetime": "2015-09-21 20:14:08",
                         "delivery_channel": "\u4fbf\u5229\u5e36",
                         "delivery_number": "GH11563",
                         "close_datetime": "2015-10-19 06:20:22",
                         "inventory_process": "1",
                         "user_name": "groupbuying",
                         "user_account": "groupbuying@109life.com",
                         "user_email": "groupbuying@109life.com",
                         "stateText": "returned"
                     }, {
                         "id": "18",
                         "activity_id": "1",
                         "activity_type": "reorder_general",
                         "consumer_user_id": "1",
                         "buyer_name": "Rex",
                         "buyer_phone_number": "0972831678",
                         "buyer_email": "chen.cyr@gmail.com",
                         "product_total_price": "17800",
                         "final_total_price": "17900",
                         "other_cost": "0",
                         "cost_type": "normal",
                         "fare": "100",
                         "fare_type": "\u5b85\u914d",
                         "fare_id": "3",
                         "discount": "0",
                         "discount_type": "normal",
                         "payment_type": "0",
                         "receiver_address": "\u53f0\u5317\u5e02\u4fe1\u7fa9\u5340\u5b89\u548c\u8def\u4e00\u6bb589\u865f",
                         "receiver_name": "Rex",
                         "receiver_phone_number": "0972831678",
                         "state": "4",
                         "create_datetime": "2015-10-19 06:20:22",
                         "pay_notify_datetime": "2015-10-19 06:20:22",
                         "serial": "20151019kk7ws",
                         "delivery_datetime": "2015-09-21 20:14:08",
                         "delivery_channel": "\u4fbf\u5229\u5e36",
                         "delivery_number": "GH11563",
                         "close_datetime": "0000-00-00 00:00:00",
                         "inventory_process": "1",
                         "user_name": "groupbuying",
                         "user_account": "groupbuying@109life.com",
                         "user_email": "groupbuying@109life.com",
                         "stateText": "completed"
                     }, {
                         "id": "19",
                         "activity_id": "2",
                         "activity_type": "reorder_groupbuying",
                         "consumer_user_id": "1",
                         "buyer_name": "Rex",
                         "buyer_phone_number": "0972831678",
                         "buyer_email": "chen.cyr@gmail.com",
                         "product_total_price": "26400",
                         "final_total_price": "26400",
                         "other_cost": "0",
                         "cost_type": "normal",
                         "fare": "0",
                         "fare_type": "\u5b85\u914d",
                         "fare_id": "3",
                         "discount": "0",
                         "discount_type": "normal",
                         "payment_type": "0",
                         "receiver_address": "\u53f0\u5317\u5e02\u4fe1\u7fa9\u5340\u5b89\u548c\u8def\u4e00\u6bb589\u865f",
                         "receiver_name": "Rex",
                         "receiver_phone_number": "0972831678",
                         "state": "4",
                         "create_datetime": "2015-10-19 06:47:39",
                         "pay_notify_datetime": "2015-10-19 06:47:39",
                         "serial": "20151019OPewM",
                         "delivery_datetime": "2015-09-21 20:14:08",
                         "delivery_channel": "\u4fbf\u5229\u5e36",
                         "delivery_number": "GH11563",
                         "close_datetime": "0000-00-00 00:00:00",
                         "inventory_process": "1",
                         "user_name": "groupbuying",
                         "user_account": "groupbuying@109life.com",
                         "user_email": "groupbuying@109life.com",
                         "stateText": "completed"
                     }],
                     "pageNo": 1,
                     "pageSize": 1000,
                     "totalPage": 1,
                     "recordCount": 4
                 }
                ', true)
            ),
            array(
                //Describe
                "Search UnifiedOrder record by OrderIds list [1,13] .",
                // params
                array("ids" => array(1,13) ),
                // expected
                json_decode('
                        {
                        "records":[
                            {
                         "id": "1",
                         "activity_id": "2",
                         "activity_type": "groupbuying",
                         "consumer_user_id": "1",
                         "buyer_name": "Rex",
                         "buyer_phone_number": "0972831678",
                         "buyer_email": "chen.cyr@gmail.com",
                         "product_total_price": "35200",
                         "final_total_price": "35200",
                         "other_cost": "0",
                         "cost_type": "normal",
                         "fare": "0",
                         "fare_type": "\u5b85\u914d",
                         "fare_id": "3",
                         "discount": "0",
                         "discount_type": "normal",
                         "payment_type": "0",
                         "receiver_address": "\u53f0\u5317\u5e02\u4fe1\u7fa9\u5340\u5b89\u548c\u8def\u4e00\u6bb589\u865f",
                         "receiver_name": "Rex",
                         "receiver_phone_number": "0972831678",
                         "state": "12",
                         "create_datetime": "2015-09-13 03:31:15",
                         "pay_notify_datetime": "2015-09-13 03:35:15",
                         "serial": "201509131Tpt2",
                         "delivery_datetime": "2015-09-21 20:14:08",
                         "delivery_channel": "\u4fbf\u5229\u5e36",
                         "delivery_number": "GH11563",
                         "close_datetime": "2015-10-19 06:47:39",
                         "inventory_process": "1",
                         "user_name": "groupbuying",
                         "user_account": "groupbuying@109life.com",
                         "user_email": "groupbuying@109life.com",
                         "stateText": "returned"
                     }, {
                         "id": "13",
                         "activity_id": "1",
                         "activity_type": "general",
                         "consumer_user_id": "1",
                         "buyer_name": "Rex",
                         "buyer_phone_number": "0972831678",
                         "buyer_email": "chen.cyr@gmail.com",
                         "product_total_price": "26700",
                         "final_total_price": "26700",
                         "other_cost": "0",
                         "cost_type": "normal",
                         "fare": "0",
                         "fare_type": "\u5b85\u914d",
                         "fare_id": "3",
                         "discount": "0",
                         "discount_type": "normal",
                         "payment_type": "0",
                         "receiver_address": "\u53f0\u5317\u5e02\u4fe1\u7fa9\u5340\u5b89\u548c\u8def\u4e00\u6bb589\u865f",
                         "receiver_name": "Rex",
                         "receiver_phone_number": "0972831678",
                         "state": "12",
                         "create_datetime": "2015-09-13 03:31:15",
                         "pay_notify_datetime": "2015-09-13 03:35:15",
                         "serial": "201509131Tpt9",
                         "delivery_datetime": "2015-09-21 20:14:08",
                         "delivery_channel": "\u4fbf\u5229\u5e36",
                         "delivery_number": "GH11563",
                         "close_datetime": "2015-10-19 06:20:22",
                         "inventory_process": "1",
                         "user_name": "groupbuying",
                         "user_account": "groupbuying@109life.com",
                         "user_email": "groupbuying@109life.com",
                         "stateText": "returned"
                     }
                        ],
                        "pageNo":1,
                        "pageSize":1000,
                        "totalPage":1,
                        "recordCount":2
                        }
                ', true)
            ),
            array(
                //Describe
                "Search UnifiedOrder record by activityIds list [1,2] .",
                // params
                array("activityIds" => array(1,2) , "activityType" => "groupbuying"),
                // expected
                json_decode('
                        {
                         "records": [{
                             "id": "1",
                             "activity_id": "2",
                             "activity_type": "groupbuying",
                             "consumer_user_id": "1",
                             "buyer_name": "Rex",
                             "buyer_phone_number": "0972831678",
                             "buyer_email": "chen.cyr@gmail.com",
                             "product_total_price": "35200",
                             "final_total_price": "35200",
                             "other_cost": "0",
                             "cost_type": "normal",
                             "fare": "0",
                             "fare_type": "\u5b85\u914d",
                             "fare_id": "3",
                             "discount": "0",
                             "discount_type": "normal",
                             "payment_type": "0",
                             "receiver_address": "\u53f0\u5317\u5e02\u4fe1\u7fa9\u5340\u5b89\u548c\u8def\u4e00\u6bb589\u865f",
                             "receiver_name": "Rex",
                             "receiver_phone_number": "0972831678",
                             "state": "12",
                             "create_datetime": "2015-09-13 03:31:15",
                             "pay_notify_datetime": "2015-09-13 03:35:15",
                             "serial": "201509131Tpt2",
                             "delivery_datetime": "2015-09-21 20:14:08",
                             "delivery_channel": "\u4fbf\u5229\u5e36",
                             "delivery_number": "GH11563",
                             "close_datetime": "2015-10-19 06:47:39",
                             "inventory_process": "1",
                             "master_id": "1",
                             "activity_name": "IPHONE\u71b1\u8ce3\u6703",
                             "master_name": "\u9673\u5955\u745e",
                             "master_bank_name": "\u7b2c\u4e00\u9280\u884c",
                             "master_bank_code": "006",
                             "master_bank_account": "0796664431222",
                             "master_bank_account_name": "\u9673\u5955\u745e",
                             "user_name": "groupbuying",
                             "user_account": "groupbuying@109life.com",
                             "user_email": "groupbuying@109life.com",
                             "stateText": "returned"
                         }, {
                             "id": "19",
                             "activity_id": "2",
                             "activity_type": "reorder_groupbuying",
                             "consumer_user_id": "1",
                             "buyer_name": "Rex",
                             "buyer_phone_number": "0972831678",
                             "buyer_email": "chen.cyr@gmail.com",
                             "product_total_price": "26400",
                             "final_total_price": "26400",
                             "other_cost": "0",
                             "cost_type": "normal",
                             "fare": "0",
                             "fare_type": "\u5b85\u914d",
                             "fare_id": "3",
                             "discount": "0",
                             "discount_type": "normal",
                             "payment_type": "0",
                             "receiver_address": "\u53f0\u5317\u5e02\u4fe1\u7fa9\u5340\u5b89\u548c\u8def\u4e00\u6bb589\u865f",
                             "receiver_name": "Rex",
                             "receiver_phone_number": "0972831678",
                             "state": "4",
                             "create_datetime": "2015-10-19 06:47:39",
                             "pay_notify_datetime": "2015-10-19 06:47:39",
                             "serial": "20151019OPewM",
                             "delivery_datetime": "2015-09-21 20:14:08",
                             "delivery_channel": "\u4fbf\u5229\u5e36",
                             "delivery_number": "GH11563",
                             "close_datetime": "0000-00-00 00:00:00",
                             "inventory_process": "1",
                             "master_id": "1",
                             "activity_name": "IPHONE\u71b1\u8ce3\u6703",
                             "master_name": "\u9673\u5955\u745e",
                             "master_bank_name": "\u7b2c\u4e00\u9280\u884c",
                             "master_bank_code": "006",
                             "master_bank_account": "0796664431222",
                             "master_bank_account_name": "\u9673\u5955\u745e",
                             "user_name": "groupbuying",
                             "user_account": "groupbuying@109life.com",
                             "user_email": "groupbuying@109life.com",
                             "stateText": "completed"
                         }],
                         "pageNo": 1,
                         "pageSize": 1000,
                         "totalPage": 1,
                         "recordCount": 2
                     }
                ', true)
            ),
            array(
                //Describe
                "Search UnifiedOrder record by  delivery_datetime  [2015-10-10 ~ 2015-10-20].",
                // params
                array("deliveryDateStart" => "2015-09-20 00:00:00", "deliveryDateEnd" => "2015-09-25 00:00:00" ),
                // expected
                json_decode('
                         {
                        "records": [{
                         "id": "1",
                         "activity_id": "2",
                         "activity_type": "groupbuying",
                         "consumer_user_id": "1",
                         "buyer_name": "Rex",
                         "buyer_phone_number": "0972831678",
                         "buyer_email": "chen.cyr@gmail.com",
                         "product_total_price": "35200",
                         "final_total_price": "35200",
                         "other_cost": "0",
                         "cost_type": "normal",
                         "fare": "0",
                         "fare_type": "\u5b85\u914d",
                         "fare_id": "3",
                         "discount": "0",
                         "discount_type": "normal",
                         "payment_type": "0",
                         "receiver_address": "\u53f0\u5317\u5e02\u4fe1\u7fa9\u5340\u5b89\u548c\u8def\u4e00\u6bb589\u865f",
                         "receiver_name": "Rex",
                         "receiver_phone_number": "0972831678",
                         "state": "12",
                         "create_datetime": "2015-09-13 03:31:15",
                         "pay_notify_datetime": "2015-09-13 03:35:15",
                         "serial": "201509131Tpt2",
                         "delivery_datetime": "2015-09-21 20:14:08",
                         "delivery_channel": "\u4fbf\u5229\u5e36",
                         "delivery_number": "GH11563",
                         "close_datetime": "2015-10-19 06:47:39",
                         "inventory_process": "1",
                         "user_name": "groupbuying",
                         "user_account": "groupbuying@109life.com",
                         "user_email": "groupbuying@109life.com",
                         "stateText": "returned"
                     }, {
                         "id": "13",
                         "activity_id": "1",
                         "activity_type": "general",
                         "consumer_user_id": "1",
                         "buyer_name": "Rex",
                         "buyer_phone_number": "0972831678",
                         "buyer_email": "chen.cyr@gmail.com",
                         "product_total_price": "26700",
                         "final_total_price": "26700",
                         "other_cost": "0",
                         "cost_type": "normal",
                         "fare": "0",
                         "fare_type": "\u5b85\u914d",
                         "fare_id": "3",
                         "discount": "0",
                         "discount_type": "normal",
                         "payment_type": "0",
                         "receiver_address": "\u53f0\u5317\u5e02\u4fe1\u7fa9\u5340\u5b89\u548c\u8def\u4e00\u6bb589\u865f",
                         "receiver_name": "Rex",
                         "receiver_phone_number": "0972831678",
                         "state": "12",
                         "create_datetime": "2015-09-13 03:31:15",
                         "pay_notify_datetime": "2015-09-13 03:35:15",
                         "serial": "201509131Tpt9",
                         "delivery_datetime": "2015-09-21 20:14:08",
                         "delivery_channel": "\u4fbf\u5229\u5e36",
                         "delivery_number": "GH11563",
                         "close_datetime": "2015-10-19 06:20:22",
                         "inventory_process": "1",
                         "user_name": "groupbuying",
                         "user_account": "groupbuying@109life.com",
                         "user_email": "groupbuying@109life.com",
                         "stateText": "returned"
                     }, {
                         "id": "18",
                         "activity_id": "1",
                         "activity_type": "reorder_general",
                         "consumer_user_id": "1",
                         "buyer_name": "Rex",
                         "buyer_phone_number": "0972831678",
                         "buyer_email": "chen.cyr@gmail.com",
                         "product_total_price": "17800",
                         "final_total_price": "17900",
                         "other_cost": "0",
                         "cost_type": "normal",
                         "fare": "100",
                         "fare_type": "\u5b85\u914d",
                         "fare_id": "3",
                         "discount": "0",
                         "discount_type": "normal",
                         "payment_type": "0",
                         "receiver_address": "\u53f0\u5317\u5e02\u4fe1\u7fa9\u5340\u5b89\u548c\u8def\u4e00\u6bb589\u865f",
                         "receiver_name": "Rex",
                         "receiver_phone_number": "0972831678",
                         "state": "4",
                         "create_datetime": "2015-10-19 06:20:22",
                         "pay_notify_datetime": "2015-10-19 06:20:22",
                         "serial": "20151019kk7ws",
                         "delivery_datetime": "2015-09-21 20:14:08",
                         "delivery_channel": "\u4fbf\u5229\u5e36",
                         "delivery_number": "GH11563",
                         "close_datetime": "0000-00-00 00:00:00",
                         "inventory_process": "1",
                         "user_name": "groupbuying",
                         "user_account": "groupbuying@109life.com",
                         "user_email": "groupbuying@109life.com",
                         "stateText": "completed"
                     }, {
                         "id": "19",
                         "activity_id": "2",
                         "activity_type": "reorder_groupbuying",
                         "consumer_user_id": "1",
                         "buyer_name": "Rex",
                         "buyer_phone_number": "0972831678",
                         "buyer_email": "chen.cyr@gmail.com",
                         "product_total_price": "26400",
                         "final_total_price": "26400",
                         "other_cost": "0",
                         "cost_type": "normal",
                         "fare": "0",
                         "fare_type": "\u5b85\u914d",
                         "fare_id": "3",
                         "discount": "0",
                         "discount_type": "normal",
                         "payment_type": "0",
                         "receiver_address": "\u53f0\u5317\u5e02\u4fe1\u7fa9\u5340\u5b89\u548c\u8def\u4e00\u6bb589\u865f",
                         "receiver_name": "Rex",
                         "receiver_phone_number": "0972831678",
                         "state": "4",
                         "create_datetime": "2015-10-19 06:47:39",
                         "pay_notify_datetime": "2015-10-19 06:47:39",
                         "serial": "20151019OPewM",
                         "delivery_datetime": "2015-09-21 20:14:08",
                         "delivery_channel": "\u4fbf\u5229\u5e36",
                         "delivery_number": "GH11563",
                         "close_datetime": "0000-00-00 00:00:00",
                         "inventory_process": "1",
                         "user_name": "groupbuying",
                         "user_account": "groupbuying@109life.com",
                         "user_email": "groupbuying@109life.com",
                         "stateText": "completed"
                     }],
                     "pageNo": 1,
                     "pageSize": 1000,
                     "totalPage": 1,
                     "recordCount": 4
                 }
                ', true)
            )
        );
    }

    /**
     * Test search fare's records
     * @dataProvider searchSpecRecordsProvider
     */
    public function testSearchSpecRecords($describe, $params, $expected) {
        echo "$describe \n\r ";
        $collection = new UnifiedOrderCollection();
        $result = $collection->searchSpecRecords(1, 1000, $params);
        $this->assertEquals($expected, $result);
    }

    public function searchSpecRecordsProvider() {
        return array(
            array(
                //Describe
                "Search UnifiedOrder spec record by keyword [32G 玫瑰金] .",
                // params
                array("keyword" => "32G 玫瑰金" ),
                // expected
                json_decode('
                   {
                        "records": [
                        {
                            "id": "1",
                            "activity_id": "2",
                            "activity_type": "groupbuying",
                            "consumer_user_id": "1",
                            "buyer_name": "Rex",
                            "buyer_phone_number": "0972831678",
                            "buyer_email": "chen.cyr@gmail.com",
                            "product_total_price": "35200",
                            "final_total_price": "35200",
                            "other_cost": "0",
                            "cost_type": "normal",
                            "fare": "0",
                            "fare_type": "\u5b85\u914d",
                            "fare_id": "3",
                            "discount": "0",
                            "discount_type": "normal",
                            "payment_type": "0",
                            "receiver_address": "\u53f0\u5317\u5e02\u4fe1\u7fa9\u5340\u5b89\u548c\u8def\u4e00\u6bb589\u865f",
                            "receiver_name": "Rex",
                            "receiver_phone_number": "0972831678",
                            "state": "12",
                            "create_datetime": "2015-09-13 03:31:15",
                            "pay_notify_datetime": "2015-09-13 03:35:15",
                            "serial": "201509131Tpt2",
                            "delivery_datetime": "2015-09-21 20:14:08",
                            "delivery_channel": "\u4fbf\u5229\u5e36",
                            "delivery_number": "GH11563",
                            "close_datetime": "2015-10-19 06:47:39",
                            "inventory_process": "1",
                            "order_id": "1",
                            "spec_id": "1",
                            "spec_amount": "2",
                            "spec_unit_price": "8800",
                            "spec_total_price": "8800",
                            "spec_fare": "0",
                            "spec_fare_type": "\u5b85\u914d",
                            "spec_other_cost": "0",
                            "spec_cost_type": "normal",
                            "spec_discount": "0",
                            "spec_discount_type": "normal",
                            "spec_activity_type": "groupbuying",
                            "spec_activity_id": "2",
                            "spec_name": "32G \u73ab\u7470\u91d1",
                            "spec_product_id": "2",
                            "spec_serial": "RX2245",
                            "product_id": "2",
                            "product_name": "iPhone 6S",
                            "weight": "100",
                            "user_name": "groupbuying",
                            "user_account": "groupbuying@109life.com",
                            "user_email": "groupbuying@109life.com",
                            "stateText": "returned"
                        }, {
                            "id": "13",
                            "activity_id": "1",
                            "activity_type": "general",
                            "consumer_user_id": "1",
                            "buyer_name": "Rex",
                            "buyer_phone_number": "0972831678",
                            "buyer_email": "chen.cyr@gmail.com",
                            "product_total_price": "26700",
                            "final_total_price": "26700",
                            "other_cost": "0",
                            "cost_type": "normal",
                            "fare": "0",
                            "fare_type": "\u5b85\u914d",
                            "fare_id": "3",
                            "discount": "0",
                            "discount_type": "normal",
                            "payment_type": "0",
                            "receiver_address": "\u53f0\u5317\u5e02\u4fe1\u7fa9\u5340\u5b89\u548c\u8def\u4e00\u6bb589\u865f",
                            "receiver_name": "Rex",
                            "receiver_phone_number": "0972831678",
                            "state": "12",
                            "create_datetime": "2015-09-13 03:31:15",
                            "pay_notify_datetime": "2015-09-13 03:35:15",
                            "serial": "201509131Tpt9",
                            "delivery_datetime": "2015-09-21 20:14:08",
                            "delivery_channel": "\u4fbf\u5229\u5e36",
                            "delivery_number": "GH11563",
                            "close_datetime": "2015-10-19 06:20:22",
                            "inventory_process": "1",
                            "order_id": "13",
                            "spec_id": "1",
                            "spec_amount": "1",
                            "spec_unit_price": "8900",
                            "spec_total_price": "8900",
                            "spec_fare": "0",
                            "spec_fare_type": "\u5b85\u914d",
                            "spec_other_cost": "0",
                            "spec_cost_type": "normal",
                            "spec_discount": "0",
                            "spec_discount_type": "normal",
                            "spec_activity_type": "general",
                            "spec_activity_id": "1",
                            "spec_name": "32G \u73ab\u7470\u91d1",
                            "spec_product_id": "2",
                            "spec_serial": "RX2245",
                            "product_id": "2",
                            "product_name": "iPhone 6S",
                            "weight": "100",
                            "user_name": "groupbuying",
                            "user_account": "groupbuying@109life.com",
                            "user_email": "groupbuying@109life.com",
                            "stateText": "returned"
                        }, {
                            "id": "19",
                            "activity_id": "2",
                            "activity_type": "reorder_groupbuying",
                            "consumer_user_id": "1",
                            "buyer_name": "Rex",
                            "buyer_phone_number": "0972831678",
                            "buyer_email": "chen.cyr@gmail.com",
                            "product_total_price": "26400",
                            "final_total_price": "26400",
                            "other_cost": "0",
                            "cost_type": "normal",
                            "fare": "0",
                            "fare_type": "\u5b85\u914d",
                            "fare_id": "3",
                            "discount": "0",
                            "discount_type": "normal",
                            "payment_type": "0",
                            "receiver_address": "\u53f0\u5317\u5e02\u4fe1\u7fa9\u5340\u5b89\u548c\u8def\u4e00\u6bb589\u865f",
                            "receiver_name": "Rex",
                            "receiver_phone_number": "0972831678",
                            "state": "4",
                            "create_datetime": "2015-10-19 06:47:39",
                            "pay_notify_datetime": "2015-10-19 06:47:39",
                            "serial": "20151019OPewM",
                            "delivery_datetime": "2015-09-21 20:14:08",
                            "delivery_channel": "\u4fbf\u5229\u5e36",
                            "delivery_number": "GH11563",
                            "close_datetime": "0000-00-00 00:00:00",
                            "inventory_process": "1",
                            "order_id": "19",
                            "spec_id": "1",
                            "spec_amount": "2",
                            "spec_unit_price": "8800",
                            "spec_total_price": "17600",
                            "spec_fare": "0",
                            "spec_fare_type": "\u5b85\u914d",
                            "spec_other_cost": "0",
                            "spec_cost_type": "normal",
                            "spec_discount": "0",
                            "spec_discount_type": "normal",
                            "spec_activity_type": "reorder_groupbuying",
                            "spec_activity_id": "2",
                            "spec_name": "32G \u73ab\u7470\u91d1",
                            "spec_product_id": "2",
                            "spec_serial": "RX2245",
                            "product_id": "2",
                            "product_name": "iPhone 6S",
                            "weight": "100",
                            "user_name": "groupbuying",
                            "user_account": "groupbuying@109life.com",
                            "user_email": "groupbuying@109life.com",
                            "stateText": "completed"
                        }],
                        "pageNo": 1,
                        "pageSize": 1000,
                        "totalPage": 1,
                        "recordCount": 3
                    }
                ', true)
            ),
            array(
                //Describe
                "Search UnifiedOrder spec record by serial [201509131Tpt2] .",
                // params
                array("serial" => "201509131Tpt2" ),
                // expected
                json_decode('
                        {
                        "records": [
                            {
                                "id": "1",
                                "activity_id": "2",
                                "activity_type": "groupbuying",
                                "consumer_user_id": "1",
                                "buyer_name": "Rex",
                                "buyer_phone_number": "0972831678",
                                "buyer_email": "chen.cyr@gmail.com",
                                "product_total_price": "35200",
                                "final_total_price": "35200",
                                "other_cost": "0",
                                "cost_type": "normal",
                                "fare": "0",
                                "fare_type": "\u5b85\u914d",
                                "fare_id": "3",
                                "discount": "0",
                                "discount_type": "normal",
                                "payment_type": "0",
                                "receiver_address": "\u53f0\u5317\u5e02\u4fe1\u7fa9\u5340\u5b89\u548c\u8def\u4e00\u6bb589\u865f",
                                "receiver_name": "Rex",
                                "receiver_phone_number": "0972831678",
                                "state": "12",
                                "create_datetime": "2015-09-13 03:31:15",
                                "pay_notify_datetime": "2015-09-13 03:35:15",
                                "serial": "201509131Tpt2",
                                "delivery_datetime": "2015-09-21 20:14:08",
                                "delivery_channel": "\u4fbf\u5229\u5e36",
                                "delivery_number": "GH11563",
                                "close_datetime": "2015-10-19 06:47:39",
                                "inventory_process": "1",
                                "order_id": "1",
                                "spec_id": "1",
                                "spec_amount": "2",
                                "spec_unit_price": "8800",
                                "spec_total_price": "8800",
                                "spec_fare": "0",
                                "spec_fare_type": "\u5b85\u914d",
                                "spec_other_cost": "0",
                                "spec_cost_type": "normal",
                                "spec_discount": "0",
                                "spec_discount_type": "normal",
                                "spec_activity_type": "groupbuying",
                                "spec_activity_id": "2",
                                "spec_name": "32G \u73ab\u7470\u91d1",
                                "spec_product_id": "2",
                                "spec_serial": "RX2245",
                                "product_id": "2",
                                "product_name": "iPhone 6S",
                                "weight": "100",
                                "user_name": "groupbuying",
                                "user_account": "groupbuying@109life.com",
                                "user_email": "groupbuying@109life.com",
                                "stateText": "returned"
                            },
                            {
                                "id": "1",
                                "activity_id": "2",
                                "activity_type": "groupbuying",
                                "consumer_user_id": "1",
                                "buyer_name": "Rex",
                                "buyer_phone_number": "0972831678",
                                "buyer_email": "chen.cyr@gmail.com",
                                "product_total_price": "35200",
                                "final_total_price": "35200",
                                "other_cost": "0",
                                "cost_type": "normal",
                                "fare": "0",
                                "fare_type": "\u5b85\u914d",
                                "fare_id": "3",
                                "discount": "0",
                                "discount_type": "normal",
                                "payment_type": "0",
                                "receiver_address": "\u53f0\u5317\u5e02\u4fe1\u7fa9\u5340\u5b89\u548c\u8def\u4e00\u6bb589\u865f",
                                "receiver_name": "Rex",
                                "receiver_phone_number": "0972831678",
                                "state": "12",
                                "create_datetime": "2015-09-13 03:31:15",
                                "pay_notify_datetime": "2015-09-13 03:35:15",
                                "serial": "201509131Tpt2",
                                "delivery_datetime": "2015-09-21 20:14:08",
                                "delivery_channel": "\u4fbf\u5229\u5e36",
                                "delivery_number": "GH11563",
                                "close_datetime": "2015-10-19 06:47:39",
                                "inventory_process": "1",
                                "order_id": "1",
                                "spec_id": "2",
                                "spec_amount": "2",
                                "spec_unit_price": "8800",
                                "spec_total_price": "8800",
                                "spec_fare": "0",
                                "spec_fare_type": "\u5b85\u914d",
                                "spec_other_cost": "0",
                                "spec_cost_type": "normal",
                                "spec_discount": "0",
                                "spec_discount_type": "normal",
                                "spec_activity_type": "groupbuying",
                                "spec_activity_id": "2",
                                "spec_name": "64G 玫瑰金",
                                "spec_product_id": "2",
                                "spec_serial": "RX2246",
                                "product_id": "2",
                                "product_name": "iPhone 6S",
                                "weight": "100",
                                "user_name": "groupbuying",
                                "user_account": "groupbuying@109life.com",
                                "user_email": "groupbuying@109life.com",
                                "stateText": "returned"
                            }
                        ],
                     "pageNo": 1,
                     "pageSize": 1000,
                     "totalPage": 1,
                     "recordCount": 2
                 }
                ', true)
            ),
            array(
                //Describe
                "Search UnifiedOrder spec record by OrderIds list [1,13] .",
                // params
                array("ids" => array(1,13) ),
                // expected
                json_decode('
                         {
                            "records": [{
                             "id": "1",
                             "activity_id": "2",
                             "activity_type": "groupbuying",
                             "consumer_user_id": "1",
                             "buyer_name": "Rex",
                             "buyer_phone_number": "0972831678",
                             "buyer_email": "chen.cyr@gmail.com",
                             "product_total_price": "35200",
                             "final_total_price": "35200",
                             "other_cost": "0",
                             "cost_type": "normal",
                             "fare": "0",
                             "fare_type": "\u5b85\u914d",
                             "fare_id": "3",
                             "discount": "0",
                             "discount_type": "normal",
                             "payment_type": "0",
                             "receiver_address": "\u53f0\u5317\u5e02\u4fe1\u7fa9\u5340\u5b89\u548c\u8def\u4e00\u6bb589\u865f",
                             "receiver_name": "Rex",
                             "receiver_phone_number": "0972831678",
                             "state": "12",
                             "create_datetime": "2015-09-13 03:31:15",
                             "pay_notify_datetime": "2015-09-13 03:35:15",
                             "serial": "201509131Tpt2",
                             "delivery_datetime": "2015-09-21 20:14:08",
                             "delivery_channel": "\u4fbf\u5229\u5e36",
                             "delivery_number": "GH11563",
                             "close_datetime": "2015-10-19 06:47:39",
                             "inventory_process": "1",
                             "order_id": "1",
                             "spec_id": "1",
                             "spec_amount": "2",
                             "spec_unit_price": "8800",
                             "spec_total_price": "8800",
                             "spec_fare": "0",
                             "spec_fare_type": "\u5b85\u914d",
                             "spec_other_cost": "0",
                             "spec_cost_type": "normal",
                             "spec_discount": "0",
                             "spec_discount_type": "normal",
                             "spec_activity_type": "groupbuying",
                             "spec_activity_id": "2",
                             "spec_name": "32G \u73ab\u7470\u91d1",
                             "spec_product_id": "2",
                             "spec_serial": "RX2245",
                             "product_id": "2",
                             "product_name": "iPhone 6S",
                             "weight": "100",
                             "user_name": "groupbuying",
                             "user_account": "groupbuying@109life.com",
                             "user_email": "groupbuying@109life.com",
                             "stateText": "returned"
                         }, {
                             "id": "1",
                             "activity_id": "2",
                             "activity_type": "groupbuying",
                             "consumer_user_id": "1",
                             "buyer_name": "Rex",
                             "buyer_phone_number": "0972831678",
                             "buyer_email": "chen.cyr@gmail.com",
                             "product_total_price": "35200",
                             "final_total_price": "35200",
                             "other_cost": "0",
                             "cost_type": "normal",
                             "fare": "0",
                             "fare_type": "\u5b85\u914d",
                             "fare_id": "3",
                             "discount": "0",
                             "discount_type": "normal",
                             "payment_type": "0",
                             "receiver_address": "\u53f0\u5317\u5e02\u4fe1\u7fa9\u5340\u5b89\u548c\u8def\u4e00\u6bb589\u865f",
                             "receiver_name": "Rex",
                             "receiver_phone_number": "0972831678",
                             "state": "12",
                             "create_datetime": "2015-09-13 03:31:15",
                             "pay_notify_datetime": "2015-09-13 03:35:15",
                             "serial": "201509131Tpt2",
                             "delivery_datetime": "2015-09-21 20:14:08",
                             "delivery_channel": "\u4fbf\u5229\u5e36",
                             "delivery_number": "GH11563",
                             "close_datetime": "2015-10-19 06:47:39",
                             "inventory_process": "1",
                             "order_id": "1",
                             "spec_id": "2",
                             "spec_amount": "2",
                             "spec_unit_price": "8800",
                             "spec_total_price": "8800",
                             "spec_fare": "0",
                             "spec_fare_type": "\u5b85\u914d",
                             "spec_other_cost": "0",
                             "spec_cost_type": "normal",
                             "spec_discount": "0",
                             "spec_discount_type": "normal",
                             "spec_activity_type": "groupbuying",
                             "spec_activity_id": "2",
                             "spec_name": "64G \u73ab\u7470\u91d1",
                             "spec_product_id": "2",
                             "spec_serial": "RX2246",
                             "product_id": "2",
                             "product_name": "iPhone 6S",
                             "weight": "100",
                             "user_name": "groupbuying",
                             "user_account": "groupbuying@109life.com",
                             "user_email": "groupbuying@109life.com",
                             "stateText": "returned"
                         }, {
                             "id": "13",
                             "activity_id": "1",
                             "activity_type": "general",
                             "consumer_user_id": "1",
                             "buyer_name": "Rex",
                             "buyer_phone_number": "0972831678",
                             "buyer_email": "chen.cyr@gmail.com",
                             "product_total_price": "26700",
                             "final_total_price": "26700",
                             "other_cost": "0",
                             "cost_type": "normal",
                             "fare": "0",
                             "fare_type": "\u5b85\u914d",
                             "fare_id": "3",
                             "discount": "0",
                             "discount_type": "normal",
                             "payment_type": "0",
                             "receiver_address": "\u53f0\u5317\u5e02\u4fe1\u7fa9\u5340\u5b89\u548c\u8def\u4e00\u6bb589\u865f",
                             "receiver_name": "Rex",
                             "receiver_phone_number": "0972831678",
                             "state": "12",
                             "create_datetime": "2015-09-13 03:31:15",
                             "pay_notify_datetime": "2015-09-13 03:35:15",
                             "serial": "201509131Tpt9",
                             "delivery_datetime": "2015-09-21 20:14:08",
                             "delivery_channel": "\u4fbf\u5229\u5e36",
                             "delivery_number": "GH11563",
                             "close_datetime": "2015-10-19 06:20:22",
                             "inventory_process": "1",
                             "order_id": "13",
                             "spec_id": "1",
                             "spec_amount": "1",
                             "spec_unit_price": "8900",
                             "spec_total_price": "8900",
                             "spec_fare": "0",
                             "spec_fare_type": "\u5b85\u914d",
                             "spec_other_cost": "0",
                             "spec_cost_type": "normal",
                             "spec_discount": "0",
                             "spec_discount_type": "normal",
                             "spec_activity_type": "general",
                             "spec_activity_id": "1",
                             "spec_name": "32G \u73ab\u7470\u91d1",
                             "spec_product_id": "2",
                             "spec_serial": "RX2245",
                             "product_id": "2",
                             "product_name": "iPhone 6S",
                             "weight": "100",
                             "user_name": "groupbuying",
                             "user_account": "groupbuying@109life.com",
                             "user_email": "groupbuying@109life.com",
                             "stateText": "returned"
                         }, {
                             "id": "13",
                             "activity_id": "1",
                             "activity_type": "general",
                             "consumer_user_id": "1",
                             "buyer_name": "Rex",
                             "buyer_phone_number": "0972831678",
                             "buyer_email": "chen.cyr@gmail.com",
                             "product_total_price": "26700",
                             "final_total_price": "26700",
                             "other_cost": "0",
                             "cost_type": "normal",
                             "fare": "0",
                             "fare_type": "\u5b85\u914d",
                             "fare_id": "3",
                             "discount": "0",
                             "discount_type": "normal",
                             "payment_type": "0",
                             "receiver_address": "\u53f0\u5317\u5e02\u4fe1\u7fa9\u5340\u5b89\u548c\u8def\u4e00\u6bb589\u865f",
                             "receiver_name": "Rex",
                             "receiver_phone_number": "0972831678",
                             "state": "12",
                             "create_datetime": "2015-09-13 03:31:15",
                             "pay_notify_datetime": "2015-09-13 03:35:15",
                             "serial": "201509131Tpt9",
                             "delivery_datetime": "2015-09-21 20:14:08",
                             "delivery_channel": "\u4fbf\u5229\u5e36",
                             "delivery_number": "GH11563",
                             "close_datetime": "2015-10-19 06:20:22",
                             "inventory_process": "1",
                             "order_id": "13",
                             "spec_id": "2",
                             "spec_amount": "2",
                             "spec_unit_price": "8900",
                             "spec_total_price": "17800",
                             "spec_fare": "0",
                             "spec_fare_type": "\u5b85\u914d",
                             "spec_other_cost": "0",
                             "spec_cost_type": "normal",
                             "spec_discount": "0",
                             "spec_discount_type": "normal",
                             "spec_activity_type": "general",
                             "spec_activity_id": "1",
                             "spec_name": "64G \u73ab\u7470\u91d1",
                             "spec_product_id": "2",
                             "spec_serial": "RX2246",
                             "product_id": "2",
                             "product_name": "iPhone 6S",
                             "weight": "100",
                             "user_name": "groupbuying",
                             "user_account": "groupbuying@109life.com",
                             "user_email": "groupbuying@109life.com",
                             "stateText": "returned"
                         }],
                         "pageNo": 1,
                         "pageSize": 1000,
                         "totalPage": 1,
                         "recordCount": 4
                     }
                ', true)
            )
        );
    }
}

?>